[package]
rust-version.workspace = true
name = "seele-tools"
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
seele-qml-core = { path = "../qml-core" }
sha2 = { workspace = true }
tempfile = { workspace = true }
seele-runtime = { workspace = true }
dbus = "0.9"
dbus-crossroads = "0.5"
libc = { workspace = true }
png = "0.17"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[[bench]]
name = "grayscale"
harness = false
