const {nativeBridge, source: nativeSource} = require("./native-functions.cjs");
const fs = require("node:fs");
const vm = require("node:vm");
const assert = require("node:assert/strict");
const focus = vm.createContext({Bridge: nativeBridge()});
vm.runInContext(nativeSource(fs.readFileSync(process.argv[2], "utf8")), focus);
let state = focus.initial();
assert.equal(state.status, "idle");
state = focus.update(state, "start", 1000, 25);
assert.equal(state.deadline, 1501000);
state = focus.update(state, "tick", 2001);
assert.equal(state.remaining, 1499);
state = focus.update(state, "pause", 3000);
assert.equal(state.status, "paused");
assert.equal(state.remaining, 1498);
assert.equal(focus.update(state, "tick", 9999999), state);
state = focus.update(state, "resume", 10000000);
assert.equal(state.deadline, 11498000);
state = focus.update(state, "tick", 12000000);
assert.equal(state.status, "done", "resume after suspend completes the deadline");
assert.equal(focus.update(state, "tick", 12000100), state, "completion is emitted once");
state = focus.update(state, "start", 13000000, 5);
assert.equal(state.duration, 300, "a new break can start after completion");
assert.equal(focus.update(state, "start", 13000000, Infinity), state);
assert.equal(focus.update(state, "start", 13000000, -1), state);
assert.equal(focus.update(state, "start", 13000000, 241), state);
assert.equal(focus.update(state, "tick", NaN), state);
assert.equal(focus.update(state, "tick", 1).remaining, 300, "clock rollback cannot exceed duration");
assert.equal(focus.update(state, "cancel", 13001000).status, "idle");
assert.equal(focus.update({status:"bad"}, "tick", 0).status, "idle");
assert.equal(focus.label(65), "01:05");
assert.equal(focus.label(0), "00:00");
assert.equal(focus.label(6000), "100:00");
const restored = JSON.parse(JSON.stringify(focus.update(null, "start", 0, 1)));
assert.equal(focus.update(restored, "tick", 61000).status, "done", "retained deadline survives QML reload");
assert.equal(focus.update(restored, "pause", 61000).status, "done", "pausing expired timer still completes");
console.log("Focus timer lifecycle checks passed");

const panel = fs.readFileSync(require("node:path").join(require("node:path").dirname(process.argv[2]), "FocusPanel.qml"), "utf8");
const handler = panel.match(/Keys.onPressed: event => \{([^]*?)\n  }/);
assert(handler, "production focus key handler exists");
const calls = [];
const context = vm.createContext({Qt:{Key_1:1,Key_2:2,Key_3:3,Key_Delete:4,Key_Space:5,Key_Plus:6,ControlModifier:1,AltModifier:2,MetaModifier:4},customMinutes:{activeFocus:false},panel:{timer:{timerState:{status:"running"},command:(...args)=>calls.push(args)}}});
vm.runInContext("function key(event) {" + handler[1] + "}", context);
context.key({key:1,modifiers:0,isAutoRepeat:true,accepted:false});
context.key({key:1,modifiers:1,isAutoRepeat:false,accepted:false});
assert.equal(calls.length, 0, "held and modified keys cannot restart the timer");
const press = {key:5,modifiers:0,isAutoRepeat:false,accepted:false};
context.key(press);
assert.equal(calls.length, 1);
assert.equal(calls[0][0], "pause");
assert.equal(press.accepted, true);
console.log("Focus keyboard guard checks passed");

context.customMinutes.activeFocus = true;
for (const key of [1, 2, 3, 4, 5, 6]) context.key({key, modifiers:0, isAutoRepeat:false});
assert.equal(calls.length, 1, "editing custom minutes cannot invoke panel shortcuts");
context.customMinutes.activeFocus = false;
context.key({key:6, modifiers:0, isAutoRepeat:false});
assert.equal(calls.at(-1)[0], "extend");
for (const input of ["", "0", "241", "1.5", "-1", "1e2", "Infinity", "12m", "9999999999999999"]) {
  assert.equal(focus.customInput(input).valid, false, input);
  assert.equal(focus.update(state, "custom", 14000000, input), state);
}
for (const input of ["1", "37", "240", " 45 "]) {
  assert.equal(focus.customInput(input).valid, true, input);
  assert.equal(focus.update(state, "custom", 14000000, input).duration, Number(input) * 60);
}
state = focus.update(null, "custom", 1000, "37");
state = focus.update(state, "extend", 2101);
assert.equal(state.duration, 42 * 60);
assert.equal(state.deadline, 2521000, "extension adds to absolute deadline, not the last rounded tick");
assert.equal(state.remaining, 2519);
state = focus.update(state, "pause", 2201);
state = focus.update(state, "extend", 9999999);
assert.equal(state.status, "paused");
assert.equal(state.deadline, 0);
assert.equal(state.remaining, 2819);
assert.equal(focus.update(state, "resume", 10000000).deadline, 12819000);
state = focus.update(null, "custom", 0, "235");
assert.equal(focus.canExtend(state), true);
state = focus.update(state, "extend", 0);
assert.equal(state.duration, 14400);
assert.equal(focus.canExtend(state), false);
assert.equal(focus.update(state, "extend", 0), state);
for (const minutes of [236, 239, 240]) {
  state = focus.update(null, "start", 0, minutes);
  assert.equal(focus.canExtend(state), false);
  assert.equal(focus.update(state, "extend", 0), state);
}
state = focus.update(null, "custom", 0, "1");
state = focus.update(state, "extend", 60000);
assert.equal(state.status, "done", "extension at expired deadline completes instead of reviving timer");
assert.equal(focus.update(state, "extend", 60001), state);
state = focus.initial();
assert.equal(focus.canExtend(state), false);
assert.equal(focus.update(state, "extend", 0), state);
console.log("Custom focus validation and extension checks passed");
