const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const notes = {};
vm.createContext(notes);
vm.runInContext(fs.readFileSync(process.argv[2], 'utf8'), notes);
const draft = { id: 'one', title: 'Newer title', body: 'unsaved text', _version: 2, _dirty: true };
const old = notes.merge({ id: 'one', title: 'Old title', body: 'old', memos: ['memo'] }, draft, 1);
assert.equal(old.body, 'unsaved text');
assert.equal(old.title, 'Newer title');
assert.equal(old._dirty, true);
assert.equal(old.memos[0], 'memo', 'new audio metadata must still arrive during editing');
assert.equal(notes.merge({ id: 'one' }, draft, 2)._dirty, false, 'only the acknowledged version becomes clean');
assert.equal(notes.merge({ id: 'one' }, draft, -1).body, 'unsaved text', 'reconnect must retain an unsaved draft');
const all = [ {title:'Trip plan',body:'Berlin hotel'}, {title:'Trip',body:'Berlin',trashed:true}, {title:'Work',body:'Meeting'} ];
assert.equal(notes.filter(all, 'BERLIN trip', false).length, 1);
assert.equal(notes.filter(all, '', true).length, 1);
assert.equal(notes.filter(all, 'absent', false).length, 0);
assert.equal(notes.duration(61000), '1:01');
assert.equal(notes.duration(-10), '0:00');
console.log('Notes search and autosave race checks passed');
