const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(process.argv[2], 'utf8');
const panel = fs.readFileSync(process.argv[3], 'utf8');
const shell = fs.readFileSync(process.argv[4], 'utf8');
const methods = [...source.matchAll(/^  function \w+\([^\n]*\) \{\n[\s\S]*?^  \}/gm)].map(m=>m[0]).join('\n');
const values = [];
let reveals = 0;
const rows = {get count(){return values.length}, get(i){return values[i]}, insert(i,v){values.splice(i,0,v)}, move(i,j){values.splice(j,0,values.splice(i,1)[0])}, setProperty(i,k,v){values[i][k]=v},remove(i){values.splice(i,1)}};
const state = vm.createContext({rows, groups:[],targets:[],selection:[],capabilities:{},error:'',actionError:'',lastFocus:'',lastFocusRevision:0,expanded:'',panelOpen:false,queue:[],payload:'',action:{running:false},revealRequested(){reveals++}, busy:false});
vm.runInContext(methods,state);
state.selectUrls(['https://example.test/file']);
assert.equal(state.queue.length,0);
assert.ok(state.actionError.includes('local'));
state.selectUrls(['file:///tmp/a%20file%0A.txt']);
assert.deepEqual(JSON.parse(state.payload),{op:'select',paths:['/tmp/a file\n.txt']});
state.enqueue({op:'send',target:'phone'});
state.enqueue({op:'send',target:'phone'});
assert.equal(state.queue.length,1,'duplicate queued activations collapse');
const group={id:'one',state:'sending',seen:true,files:[]};
state.accept({version:1,groups:[group],targets:[],selection:[]});
const identity=rows.get(0).entry;
state.accept({version:1,groups:[{...group}],targets:[],selection:[]});
assert.equal(rows.get(0).entry,identity,'unchanged snapshots preserve delegate data');
state.accept({version:1,groups:[{...group,id:'two'},group],focus:'one'});
assert.equal(rows.get(1).entry,identity,'reordering keeps existing data');
assert.equal(state.expanded,'one');
assert.equal(reveals,1);
state.accept({version:1,groups:[group],focus:'one'});
assert.equal(reveals,1,'notification focus is not repeated by polling');
state.expanded = '';
state.accept({version:1,groups:[group],focus:'one',focusRevision:1});
assert.equal(reveals,2,'another explicit notification activation focuses the same group again');
assert.equal(state.expanded,'one');
assert.match(shell,/function openTransfers\(\): void \{ if \(root.controlPanel !== "transfers"\)/, 'external open is idempotent');
state.accept({version:1,groups:[],error:'service-unavailable'});
assert.equal(rows.count,0,'a stopped service clears stale controls');
assert.match(panel,/fileMode: FileDialog.OpenFiles/);
assert.match(panel,/DropArea/);
assert.match(panel,/"open", "reveal", "move", "trash"/);
assert.match(shell,/visible: transfersStore.attention/);
assert.match(shell,/TransfersPanel \{ theme: root; store: transfersStore/);
assert.match(shell,/label: "Transfers"/);
assert.doesNotMatch(panel,/tailscale|file-put|file-targets/,'UI stays provider-neutral');
console.log('Transfers selection, duplicate actions, stable rows, notification focus and production wiring passed');

const openBody = shell.match(/function openTransfers\(\): void \{([^\n]+)\}/)[1];
let toggles = 0;
const desktop = {controlPanel:'',toggleControl(name){toggles++;this.controlPanel=this.controlPanel===name?'':name}};
const ipc = vm.createContext({root:desktop});
vm.runInContext('function open(){'+openBody+'}',ipc);
ipc.open(); // QML notification focus can open first.
ipc.open(); // CLI notification action can arrive second.
assert.equal(desktop.controlPanel,'transfers');
assert.equal(toggles,1,'notification/picker external open cannot close an already-open panel');
